# image: python:3.9
image: docker:latest

stages:
  - build

before_script:
  - pip install pyinstaller

build:
  stage: build
  image: mcr.microsoft.com/windows/servercore:ltsc2022
  script:
    - pyinstaller --onefile hello_world.py
  artifacts:
    paths:
      - /builds/cherrydev/temp_docker/dist/hello_world.exe
      # - dist/hello_world.exe
  only:
    - main
    - master

